version: "3.7"

services:

  eim-proxy:
    build:
      context: ./docker/eim-proxy/.
    image: eim-proxy
    container_name: eim-proxy
    hostname: eim-proxy
    ports:
      - "80:80"
    networks:
      - eim-service
      - eim-core
    environment:
      - EIM_NGINX_HOST
      - TZ

  eim-core:
    build:
      context: ./docker/eim-core/.
    image: eim-core
    container_name: eim-core
    hostname: eim-core
    depends_on:
      - eim-mongodb
      - eim-proxy
    networks:
      - backend
      - eim-core
    environment:
      - EIM_DB_HOST
      - EIM_DB_PORT
      - EIM_DB_NAME
      - EIM_DB_USER
      - EIM_DB_PASSWORD
      - "TZ=Europe/Stockholm"

  eim-mongodb:
    build:
      context: ./docker/eim-mongodb/.
    image: eim-mongodb
    container_name: eim-mongodb
    hostname: eim-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - EIM_DB_NAME
      - EIM_DB_USER
      - EIM_DB_PASSWORD
      - TZ=Europe/Stockholm
    networks:
      - backend
    volumes:
      - "mongodb:/data/db"
    restart: unless-stopped

  eim-harvester:
    build:
      context: ./docker/eim-harvester/.
    image: eim-harvester
    container_name: eim-harvester
    hostname: eim-harvester
    depends_on:
      - eim-mongodb
    networks:
      - eim-core
    environment:
      - "EIM_HARVESTER_PERIODICITY_SEC=10"

networks:
  eim-service:
  eim-core:
  backend:
    internal: true

volumes:
  mongodb:

