timezone: Europe/Stockholm
ansible_become: true
service_user: eim
systemd_enabled: true
target_folder: "/opt/{{ service_name }}"
uri_expected: http://api.dmrdream.com/system/info
eim_docker_core: "smangelsen/eim-core:{{ dmr_release_name }}"
eim_docker_db: "smangelsen/eim-mongodb:{{ dmr_release_name }}"
eim_docker_harvester: "smangelsen/eim-harvester:{{ dmr_release_name }}"
eim_log_level: INFO
eim_harvester_periodicity: 3600