timezone: Europe/Stockholm
ansible_become: true
service_user: eim
systemd_enabled: true
target_folder: "/opt/{{ service_name }}"
eim_host: "api.dmrdream.com"
conn_check_url: "{{ eim_proto }}://{{ eim_host }}{{ conn_check_uri }}"

eim_docker_proxy: "smangelsen/eim-proxy:{{ dmr_release_name }}"
eim_docker_core: "smangelsen/eim-core:{{ dmr_release_name }}"
eim_docker_db: "smangelsen/eim-mongodb:{{ dmr_release_name }}"
eim_docker_harvester: "smangelsen/eim-harvester:{{ dmr_release_name }}"
eim_log_level: INFO
eim_harvester_periodicity: 3600
